-- ============================================================
-- V2 - Create Wardrobe Tables
-- ============================================================


-- ============================================================
-- CATEGORIES
-- Hierarchical structure:
-- Department -> Category -> Subcategory
-- ============================================================

CREATE TABLE categories (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                            name VARCHAR(100) NOT NULL,

                            slug VARCHAR(100) NOT NULL UNIQUE,

                            parent_id BIGINT,

                            CONSTRAINT fk_categories_parent
                                FOREIGN KEY (parent_id)
                                    REFERENCES categories(id)
                                    ON DELETE RESTRICT
);


-- ============================================================
-- LEVEL 1: DEPARTMENTS
-- ============================================================

INSERT INTO categories (name, slug)
VALUES
    ('Women', 'women'),
    ('Men', 'men'),
    ('Kids', 'kids'),
    ('Unisex', 'unisex');


-- ============================================================
-- LEVEL 2: WOMEN CATEGORIES
-- ============================================================

INSERT INTO categories (name, parent_id, slug)
VALUES
    (
        'Tops',
        (SELECT id FROM categories WHERE slug = 'women'),
        'women-tops'
    ),
    (
        'Bottoms',
        (SELECT id FROM categories WHERE slug = 'women'),
        'women-bottoms'
    ),
    (
        'Dresses & Jumpsuits',
        (SELECT id FROM categories WHERE slug = 'women'),
        'women-dresses-jumpsuits'
    ),
    (
        'Outerwear',
        (SELECT id FROM categories WHERE slug = 'women'),
        'women-outerwear'
    ),
    (
        'Activewear',
        (SELECT id FROM categories WHERE slug = 'women'),
        'women-activewear'
    ),
    (
        'Sleep & Lounge',
        (SELECT id FROM categories WHERE slug = 'women'),
        'women-sleep-lounge'
    ),
    (
        'Swimwear',
        (SELECT id FROM categories WHERE slug = 'women'),
        'women-swimwear'
    ),
    (
        'Intimates',
        (SELECT id FROM categories WHERE slug = 'women'),
        'women-intimates'
    ),
    (
        'Socks & Hosiery',
        (SELECT id FROM categories WHERE slug = 'women'),
        'women-socks-hosiery'
    ),
    (
        'Shoes',
        (SELECT id FROM categories WHERE slug = 'women'),
        'women-shoes'
    ),
    (
        'Bags',
        (SELECT id FROM categories WHERE slug = 'women'),
        'women-bags'
    ),
    (
        'Accessories',
        (SELECT id FROM categories WHERE slug = 'women'),
        'women-accessories'
    );


-- ============================================================
-- LEVEL 3: TOPS
-- ============================================================

INSERT INTO categories (name, parent_id, slug)
VALUES
    (
        'T-Shirts',
        (SELECT id FROM categories WHERE slug = 'women-tops'),
        'women-tshirts'
    ),
    (
        'Blouses',
        (SELECT id FROM categories WHERE slug = 'women-tops'),
        'women-blouses'
    ),
    (
        'Tank Tops',
        (SELECT id FROM categories WHERE slug = 'women-tops'),
        'women-tank-tops'
    ),
    (
        'Sweaters',
        (SELECT id FROM categories WHERE slug = 'women-tops'),
        'women-sweaters'
    ),
    (
        'Hoodies',
        (SELECT id FROM categories WHERE slug = 'women-tops'),
        'women-hoodies'
    );


-- ============================================================
-- LEVEL 3: BOTTOMS
-- ============================================================

INSERT INTO categories (name, parent_id, slug)
VALUES
    (
        'Jeans',
        (SELECT id FROM categories WHERE slug = 'women-bottoms'),
        'women-jeans'
    ),
    (
        'Trousers',
        (SELECT id FROM categories WHERE slug = 'women-bottoms'),
        'women-trousers'
    ),
    (
        'Shorts',
        (SELECT id FROM categories WHERE slug = 'women-bottoms'),
        'women-shorts'
    ),
    (
        'Skirts',
        (SELECT id FROM categories WHERE slug = 'women-bottoms'),
        'women-skirts'
    ),
    (
        'Leggings',
        (SELECT id FROM categories WHERE slug = 'women-bottoms'),
        'women-leggings'
    ),
    (
        'Joggers',
        (SELECT id FROM categories WHERE slug = 'women-bottoms'),
        'women-joggers'
    );


-- ============================================================
-- LEVEL 3: DRESSES & JUMPSUITS
-- ============================================================

INSERT INTO categories (name, parent_id, slug)
VALUES
    (
        'Casual Dresses',
        (SELECT id FROM categories WHERE slug = 'women-dresses-jumpsuits'),
        'women-casual-dresses'
    ),
    (
        'Evening Dresses',
        (SELECT id FROM categories WHERE slug = 'women-dresses-jumpsuits'),
        'women-evening-dresses'
    ),
    (
        'Work Dresses',
        (SELECT id FROM categories WHERE slug = 'women-dresses-jumpsuits'),
        'women-work-dresses'
    ),
    (
        'Jumpsuits',
        (SELECT id FROM categories WHERE slug = 'women-dresses-jumpsuits'),
        'women-jumpsuits'
    ),
    (
        'Rompers',
        (SELECT id FROM categories WHERE slug = 'women-dresses-jumpsuits'),
        'women-rompers'
    );


-- ============================================================
-- LEVEL 3: OUTERWEAR
-- ============================================================

INSERT INTO categories (name, parent_id, slug)
VALUES
    (
        'Jackets',
        (SELECT id FROM categories WHERE slug = 'women-outerwear'),
        'women-jackets'
    ),
    (
        'Coats',
        (SELECT id FROM categories WHERE slug = 'women-outerwear'),
        'women-coats'
    ),
    (
        'Blazers',
        (SELECT id FROM categories WHERE slug = 'women-outerwear'),
        'women-blazers'
    ),
    (
        'Vests',
        (SELECT id FROM categories WHERE slug = 'women-outerwear'),
        'women-vests'
    );


-- ============================================================
-- LEVEL 3: INTIMATES
-- ============================================================

INSERT INTO categories (name, parent_id, slug)
VALUES
    (
        'Bras',
        (SELECT id FROM categories WHERE slug = 'women-intimates'),
        'women-bras'
    ),
    (
        'Underwear',
        (SELECT id FROM categories WHERE slug = 'women-intimates'),
        'women-underwear'
    ),
    (
        'Shapewear',
        (SELECT id FROM categories WHERE slug = 'women-intimates'),
        'women-shapewear'
    ),
    (
        'Camisoles',
        (SELECT id FROM categories WHERE slug = 'women-intimates'),
        'women-camisoles'
    );


-- ============================================================
-- LEVEL 3: SOCKS & HOSIERY
-- ============================================================

INSERT INTO categories (name, parent_id, slug)
VALUES
    (
        'Socks',
        (SELECT id FROM categories WHERE slug = 'women-socks-hosiery'),
        'women-socks'
    ),
    (
        'Tights',
        (SELECT id FROM categories WHERE slug = 'women-socks-hosiery'),
        'women-tights'
    ),
    (
        'Stockings',
        (SELECT id FROM categories WHERE slug = 'women-socks-hosiery'),
        'women-stockings'
    );


-- ============================================================
-- LEVEL 3: SHOES
-- ============================================================

INSERT INTO categories (name, parent_id, slug)
VALUES
    (
        'Sneakers',
        (SELECT id FROM categories WHERE slug = 'women-shoes'),
        'women-sneakers'
    ),
    (
        'Boots',
        (SELECT id FROM categories WHERE slug = 'women-shoes'),
        'women-boots'
    ),
    (
        'Sandals',
        (SELECT id FROM categories WHERE slug = 'women-shoes'),
        'women-sandals'
    ),
    (
        'Heels',
        (SELECT id FROM categories WHERE slug = 'women-shoes'),
        'women-heels'
    ),
    (
        'Flats',
        (SELECT id FROM categories WHERE slug = 'women-shoes'),
        'women-flats'
    ),
    (
        'Mules',
        (SELECT id FROM categories WHERE slug = 'women-shoes'),
        'women-mules'
    ),
    (
        'Wedges',
        (SELECT id FROM categories WHERE slug = 'women-shoes'),
        'women-wedges'
    );


-- ============================================================
-- LEVEL 3: BAGS
-- ============================================================

INSERT INTO categories (name, parent_id, slug)
VALUES
    (
        'Handbags',
        (SELECT id FROM categories WHERE slug = 'women-bags'),
        'women-handbags'
    ),
    (
        'Crossbody Bags',
        (SELECT id FROM categories WHERE slug = 'women-bags'),
        'women-crossbody-bags'
    ),
    (
        'Tote Bags',
        (SELECT id FROM categories WHERE slug = 'women-bags'),
        'women-tote-bags'
    ),
    (
        'Backpacks',
        (SELECT id FROM categories WHERE slug = 'women-bags'),
        'women-backpacks'
    ),
    (
        'Clutches',
        (SELECT id FROM categories WHERE slug = 'women-bags'),
        'women-clutches'
    ),
    (
        'Wallets',
        (SELECT id FROM categories WHERE slug = 'women-bags'),
        'women-wallets'
    );


-- ============================================================
-- LEVEL 3: ACCESSORIES
-- ============================================================

INSERT INTO categories (name, parent_id, slug)
VALUES
    (
        'Belts',
        (SELECT id FROM categories WHERE slug = 'women-accessories'),
        'women-belts'
    ),
    (
        'Hats',
        (SELECT id FROM categories WHERE slug = 'women-accessories'),
        'women-hats'
    ),
    (
        'Scarves',
        (SELECT id FROM categories WHERE slug = 'women-accessories'),
        'women-scarves'
    ),
    (
        'Jewelry',
        (SELECT id FROM categories WHERE slug = 'women-accessories'),
        'women-jewelry'
    ),
    (
        'Sunglasses',
        (SELECT id FROM categories WHERE slug = 'women-accessories'),
        'women-sunglasses'
    );


-- ============================================================
-- TAGS
-- Tags belong to a specific user.
-- ============================================================

CREATE TABLE tags (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                      user_id BIGINT NOT NULL,

                      name VARCHAR(50) NOT NULL,

                      CONSTRAINT fk_tags_user
                          FOREIGN KEY (user_id)
                              REFERENCES users(id)
                              ON DELETE CASCADE,

                      CONSTRAINT uk_tags_user_name
                          UNIQUE (user_id, name)
);


-- ============================================================
-- CLOTHING ITEMS
-- Each clothing item belongs to one user and one category.
-- ============================================================

CREATE TABLE clothing_items (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                user_id BIGINT NOT NULL,

                                category_id BIGINT NOT NULL,

                                name VARCHAR(100) NOT NULL,

                                brand VARCHAR(100),

                                color VARCHAR(50),

                                size VARCHAR(30),

                                image_path VARCHAR(500),

                                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                CONSTRAINT fk_clothing_items_user
                                    FOREIGN KEY (user_id)
                                        REFERENCES users(id)
                                        ON DELETE CASCADE,

                                CONSTRAINT fk_clothing_items_category
                                    FOREIGN KEY (category_id)
                                        REFERENCES categories(id)
                                        ON DELETE RESTRICT
);


-- ============================================================
-- CLOTHING ITEMS <-> TAGS
-- Many-to-many relationship.
-- ============================================================

CREATE TABLE clothing_item_tags (
                                    clothing_item_id BIGINT NOT NULL,

                                    tag_id BIGINT NOT NULL,

                                    PRIMARY KEY (clothing_item_id, tag_id),

                                    CONSTRAINT fk_clothing_item_tags_item
                                        FOREIGN KEY (clothing_item_id)
                                            REFERENCES clothing_items(id)
                                            ON DELETE CASCADE,

                                    CONSTRAINT fk_clothing_item_tags_tag
                                        FOREIGN KEY (tag_id)
                                            REFERENCES tags(id)
                                            ON DELETE CASCADE
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_categories_parent_id
    ON categories(parent_id);

CREATE INDEX idx_tags_user_id
    ON tags(user_id);

CREATE INDEX idx_clothing_items_user_id
    ON clothing_items(user_id);

CREATE INDEX idx_clothing_items_category_id
    ON clothing_items(category_id);

CREATE INDEX idx_clothing_item_tags_tag_id
    ON clothing_item_tags(tag_id);